[package]
edition = "2024"
name = "parari"
version = "0.1.0"

[dependencies]
thiserror = "2"
tokio = { version = "1.48.0", features = ["rt", "macros", "process"] }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["rt", "macros", "process", "sync"] }
